// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_watcher.go -package=mocks -source=server.go Watcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	health "github.com/stacklok/toolhive/pkg/vmcp/health"
	gomock "go.uber.org/mock/gomock"
)

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// WaitForCacheSync mocks base method.
func (m *MockWatcher) WaitForCacheSync(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForCacheSync", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WaitForCacheSync indicates an expected call of WaitForCacheSync.
func (mr *MockWatcherMockRecorder) WaitForCacheSync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForCacheSync", reflect.TypeOf((*MockWatcher)(nil).WaitForCacheSync), ctx)
}

// MockstatusChangeRegistrar is a mock of statusChangeRegistrar interface.
type MockstatusChangeRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockstatusChangeRegistrarMockRecorder
	isgomock struct{}
}

// MockstatusChangeRegistrarMockRecorder is the mock recorder for MockstatusChangeRegistrar.
type MockstatusChangeRegistrarMockRecorder struct {
	mock *MockstatusChangeRegistrar
}

// NewMockstatusChangeRegistrar creates a new mock instance.
func NewMockstatusChangeRegistrar(ctrl *gomock.Controller) *MockstatusChangeRegistrar {
	mock := &MockstatusChangeRegistrar{ctrl: ctrl}
	mock.recorder = &MockstatusChangeRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatusChangeRegistrar) EXPECT() *MockstatusChangeRegistrarMockRecorder {
	return m.recorder
}

// AddOnStatusChange mocks base method.
func (m *MockstatusChangeRegistrar) AddOnStatusChange(arg0 func(health.StatusChangeEvent)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddOnStatusChange", arg0)
}

// AddOnStatusChange indicates an expected call of AddOnStatusChange.
func (mr *MockstatusChangeRegistrarMockRecorder) AddOnStatusChange(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOnStatusChange", reflect.TypeOf((*MockstatusChangeRegistrar)(nil).AddOnStatusChange), arg0)
}
