{{- if .Values.operator.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "toolhive-operator.fullname" . }}
  labels:
    {{- include "toolhive-operator.labels" . | nindent 4 }}
spec:
  {{- with .Values.operator.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.operator.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "toolhive-operator.selectorLabels" . | nindent 6 }}
{{- end }}
